### ISSUE TITLE
backslash on Windows

### ISSUE THREAD

**Issue by WolfgangKluge** [ben-eb/postcss-normalize-url#1]
You use `path.normalize(url)` to normalize non-absolute paths like `/img/xyz.png` or `../img/xyz.png`.
[`path.normalize(url)` always returns backslashes on Windows](https://nodejs.org/api/path.html#path_path_normalize_p) - and thus you'll get `\img\xyz.png` instead...

**Comment by ben-eb** [comment]
Good catch. :smile:

**Comment by ben-eb** [comment]
@WolfgangKluge Thanks for reporting. `2.0.2` is live on npm, I'll be releasing cssnano v2 at some time this week which will land the fix.
